// Kept apart from the schema so the same arrays populate the selects and
// validate a submission.

export const GENDERS = [
  "Female",
  "Male",
  "Non-binary",
  "Other",
  "Prefer not to say",
] as const;

export const LANGUAGES = [
  "Thai",
  "English",
  "Mandarin Chinese",
  "Burmese",
  "Khmer",
  "Lao",
  "Vietnamese",
  "Malay",
  "Bahasa Indonesia",
  "Japanese",
  "Korean",
  "Hindi",
  "Arabic",
  "French",
  "German",
  "Spanish",
  "Russian",
  "Other",
] as const;

export const NATIONALITIES = [
  "Thai",
  "Myanmar",
  "Cambodian",
  "Lao",
  "Vietnamese",
  "Malaysian",
  "Singaporean",
  "Indonesian",
  "Filipino",
  "Chinese",
  "Taiwanese",
  "Hong Konger",
  "Japanese",
  "South Korean",
  "Indian",
  "Bangladeshi",
  "Nepali",
  "Pakistani",
  "Sri Lankan",
  "Australian",
  "New Zealander",
  "American",
  "Canadian",
  "Mexican",
  "Brazilian",
  "Argentinian",
  "British",
  "Irish",
  "French",
  "German",
  "Dutch",
  "Belgian",
  "Swiss",
  "Austrian",
  "Italian",
  "Spanish",
  "Portuguese",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Polish",
  "Czech",
  "Russian",
  "Ukrainian",
  "Turkish",
  "Israeli",
  "Emirati",
  "Saudi Arabian",
  "Egyptian",
  "South African",
  "Nigerian",
  "Kenyan",
  "Other",
] as const;

export const RELIGIONS = [
  "Buddhism",
  "Christianity",
  "Islam",
  "Hinduism",
  "Judaism",
  "Sikhism",
  "No religion",
  "Prefer not to say",
  "Other",
] as const;

export const RELATIONSHIPS = [
  "Spouse / Partner",
  "Parent",
  "Child",
  "Sibling",
  "Relative",
  "Friend",
  "Legal guardian",
  "Other",
] as const;
